M48
; DRILL file {KiCad (6.0.0-0)} date Thursday, February 10, 2022 at 12:31:11 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-10T00:31:11-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X4.0638Y-3.313
X4.0669Y-4.5472
X5.4701Y-4.5496
X5.4709Y-3.313
T0
M30
