const { read, write } = require("../control-words");
const { FETCH_INSTRUCTION } = require("./mixins");
const {
  ADDRESS_MODES: {
    REGISTER_ADDRESS_MODE,
    INDIRECT_REGISTER_ADDRESS_MODE,
    IMMEDIATE_ADDRESS_MODE,
    INDIRECT_ADDRESS_MODE,
  },
} = require("./constants");

const STACK = {
  "PUSH A": {
    opcode: "0x40",
    mnemonic: "push a",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "PUSH C": {
    opcode: "0x41",
    mnemonic: "push c",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "PUSH D": {
    opcode: "0x42",
    mnemonic: "push d",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "PUSH F": {
    opcode: "0x43",
    mnemonic: "push f",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "PUSH FLAGS": {
    opcode: "0x44",
    mnemonic: "push flags",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "PUSH DS": {
    opcode: "0x45",
    mnemonic: "push ds",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "PUSH SS": {
    opcode: "0x46",
    mnemonic: "push ss",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "PUSH IMM": {
    opcode: "0x47",
    mnemonic: "push imm8",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "PUSH IMM16": {
    opcode: "0x48",
    mnemonic: "push imm16",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "POP A": {
    opcode: "0x50",
    mnemonic: "pop a",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "POP C": {
    opcode: "0x51",
    mnemonic: "pop c",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "POP D": {
    opcode: "0x52",
    mnemonic: "pop d",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "POP F": {
    opcode: "0x53",
    mnemonic: "pop f",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "POP FLAGS": {
    opcode: "0x54",
    mnemonic: "pop flags",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "POP DS": {
    opcode: "0x55",
    mnemonic: "pop ds",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
  "POP SS": {
    opcode: "0x56",
    mnemonic: "pop ss",
    description: "",
    addressMode: undefined,
    steps: [...FETCH_INSTRUCTION, "TODO"],
    flagsAffected: [],
  },
};

module.exports = {
  ...STACK,
};
