M48
; DRILL file {KiCad (6.0.0-0)} date Sunday, January 09, 2022 at 12:32:38 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-09T00:32:38-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X3.62Y-2.38
X3.62Y-4.55
X5.93Y-2.38
X5.93Y-4.55
T0
M30
